# Generated by Django 4.1.5 on 2023-01-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0003_rename_user_add_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_User',
            new_name='User',
        ),
    ]
